\repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
        args: ['--unsafe'] 
      - id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        args: [--fix]
        files: ^backend/
        types: [python]
      - id: ruff-format
        files: ^backend/
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.2
    hooks:
      - id: mypy
        files: ^backend/
        args: [--config-file=backend/pyproject.toml]
        additional_dependencies: [django-stubs]


  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/
        types_or: [javascript, jsx, ts, tsx, json, css, scss, html, markdown]
        additional_dependencies:
          - prettier@^3.0.0

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.17.0
    hooks:
      - id: eslint
        files: ^frontend/.*\.[jt]sx?$  # .js, .jsx, .ts, .tsx
        types: [file]
        args: [--fix]
        additional_dependencies:
          - eslint@^9.36.0
          - typescript@~5.9.3
          - typescript-eslint@^8.45.0
          - eslint-plugin-react-hooks@^5.2.0
          - eslint-plugin-react-refresh@^0.4.22
